# poner funcion de precondiciones




def MTC_SURSGE_030_steps(sge_funct, data, img_valeInterno, img_folioEmbarque):

    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text(data["sucursal_origen"])
    sge_funct.validar_sucursal_seleccionada(data["sucursal_origen"])
    print("3 Teclear input")
    sge_funct.press_enter()
    print("4 Teclear input")
    sge_funct.send_text('2')
    print("5 Teclear input")
    sge_funct.press_enter()
    print("6 Seleccionar <<OPCION MENU>>")
    sge_funct.send_text('4')
    print("7 Teclear input ")
    sge_funct.press_enter()
    print("8 Seleccionar <<OPCION MENU>>")
    sge_funct.send_text('3')
    print("9 Teclear input")
    sge_funct.press_enter()
    print("10 Teclear input")
    sge_funct.send_text(data["sucursal_destino"])
    print("11 Teclear input")
    sge_funct.press_enter()
    print("12 Teclear input")
    sge_funct.press_enter()
    print("13 Teclear input")
    sge_funct.press_enter()
    print("14 Teclear input")
    sge_funct.press_enter()
    print("15 Teclear input")
    sge_funct.press_enter()
    print("16 Flecha abajo para posicionarnos en el tipo de traspaso urgente")
    sge_funct.flecha_abajo()
    print("17 Flecha abajo para posicionarnos en el tipo de stock")
    sge_funct.flecha_abajo()
    print("18 Teclear input")
    sge_funct.press_enter()
    print("19 Flecha abajo para posicionarnos en Captura manual")
    sge_funct.flecha_abajo()
    print("20 Teclear input")
    sge_funct.press_enter()
    print("21 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("22 Leer archivo traspaso_stock.json para capturar la linea del producto (LINEA 31) EJEMPLO")
    sge_funct.send_text(data["linea"])
    print("23 Teclear input")
    sge_funct.press_enter()
    print("24 Leer archivo traspaso_stock.json para capturar el codigo (1000) EJEMPLO")
    sge_funct.send_text(data["codigo"])
    print("25 Teclear input")
    sge_funct.press_enter()
    print("26 Leer archivo traspaso_stock.json para capturar el almacen (01) EJEMPLO")
    sge_funct.send_text(data["almacen"])
    print("27 Teclear input")
    sge_funct.press_enter()
    print("28 Leer archivo traspaso_stock.json para capturar la cantidad (1) EJEMPLO")
    sge_funct.send_text(data["cantidad_a_mover"])
    print("29 Teclear input")
    sge_funct.press_enter()
    print("30 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    sge_funct.segundos_de_espera(3)
    print("31 Guardar el Vale Interno dando doble clic en el Vale")
    vale_interno = sge_funct.doubleclick_axis_y(img_valeInterno,20)
    print("----------------------------")
    print(f"Vale Interno: {vale_interno}")
    print("----------------------------")
    print("32 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("33 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("34 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("35 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("36 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text(data["sucursal_origen"])
    sge_funct.validar_sucursal_seleccionada(data["sucursal_origen"])
    print("37 Teclear input")
    sge_funct.press_enter()
    print("38 Ingresar en el teclado el numero de pedidos e inventarios")
    sge_funct.send_text('4')
    print("39 Teclear input")
    sge_funct.press_enter()
    print("40 ingresar en el teclado la opcion de control de embarques")
    sge_funct.send_text('11')
    print("41 Teclear input ")
    sge_funct.press_enter()
    print("42 Teclear input")
    sge_funct.send_text('2')
    print("43 Teclear input")
    sge_funct.press_enter()
    print("44 ingresar en el teclado la opcion de Asignacion de documentos para surtido")
    sge_funct.send_text('1')
    print("45 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(7)#25
    print("46 Pegar el folio del traspaso")
    sge_funct.send_text(vale_interno)
    print("47 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)
    print("48 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("49 Teclear input")
    sge_funct.send_text(data["clave_surtidor"])
    print("50 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)
    print("51 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("52 ingresar en el teclado la opcion de 3# Marcar  Documentos como surtidos")
    sge_funct.send_text('3')
    print("53 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)
    print("54 Pegar el folio del traspaso")
    sge_funct.send_text(vale_interno)
    sge_funct.segundos_de_espera(3)
    print("56 Teclear input")
    sge_funct.press_enter()
    print("57 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("58 Teclear input")
    sge_funct.send_text(data["clave_surtidor"])
    print("59 Teclear input")
    sge_funct.press_enter()
    print("60 ingresar el usuario de almacen")
    sge_funct.press_enter()
    print("60.1 ingresar la contraseña del usuario de almacen")
    sge_funct.send_text(data["password_almacen"])
    print("61 Teclear input")
    sge_funct.press_enter()
    print("62 Teclear input")
    sge_funct.press_enter()
    print("63 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("64 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("65 ingresar en el teclado la opcion de 3) Control de empaque")
    sge_funct.send_text('3')
    print("66 Teclear input")
    sge_funct.press_enter()
    print("67 ingresar en el teclado la opcion de 1) Documentos por empacar")
    sge_funct.send_text('1')
    print("68 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(7)#25
    print("69 Pegar el folio del traspaso")
    sge_funct.send_text(vale_interno)
    print("71 Teclear input")
    sge_funct.press_enter()
    print("72 Presionar la combinacion de teclas: Ctrl + w") # <------------------ aqui falla
    sge_funct.press_hotkeys('ctrl+w')
    print("73 Teclear input")
    sge_funct.send_text(data["clave_empacador"])
    print("74 Teclear input")
    sge_funct.press_enter()
    print("75 ingresar el usuario de almacen")
    sge_funct.press_enter()
    print("75.1 ingresar la contraseña del usuario de almacen")
    sge_funct.send_text(data["password_almacen"])
    print("76 Teclear input")
    sge_funct.press_enter()
    print("77 Teclear input")
    sge_funct.press_enter()
    #validar imagen tiene documentos en proceso de surtido
    print("78 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("79 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("80 ingresar en el teclado la opcion de 4) Termino de Empaque")
    sge_funct.send_text('4')
    print("81 Teclear input")
    sge_funct.press_enter()
    print("82 ingresar en el teclado la opcion de 1) Documentos por empacar")
    sge_funct.send_text('1')
    print("83 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(7)
    print("84 Pegar el folio del traspaso")
    sge_funct.send_text(vale_interno)
    print("86 Teclear input")
    sge_funct.press_enter()
    print("87 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("88 Teclear input")
    sge_funct.send_text(data["clave_empacador"])# clave empacador
    print("89 Teclear input")
    sge_funct.press_enter()
    print("90 ingresar la contraseña del usuario de almacen")
    sge_funct.send_text(data["password_almacen"])
    print("91 Teclear input")
    sge_funct.press_enter()
    print("92 Teclear input")
    sge_funct.press_enter()
    print("93 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("94 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("95 ingresar en el teclado la opcion de 5) Ordenes de embarque")
    sge_funct.send_text('5')
    print("96 Teclear input")
    sge_funct.press_enter()
    print("97 Flecha arriba para posicionarnos en la opcion TRASPASOS")
    sge_funct.flecha_arriba()
    print("98 Teclear input")
    sge_funct.press_enter()
    print("99 Teclear input para pegar el vale de traspaso")
    sge_funct.send_text(vale_interno)
    print("101 Teclear input")
    sge_funct.press_enter()
    print("102 Teclear input")
    sge_funct.press_enter()
    print("103 Teclear input")
    sge_funct.send_text(data["peso_embarque"])
    print("104 Teclear input")
    sge_funct.press_enter()
    print("105 Teclear input")
    sge_funct.send_text('1')
    print("106 Teclear input")
    sge_funct.press_enter()
    print("107 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("108 Teclear input")
    sge_funct.send_text(data["identificador_caja"])
    print("109 Teclear input")
    sge_funct.press_enter()
    print("110 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("111 Flecha abajo para el tipo de entrega OCURRE")
    sge_funct.flecha_abajo()
    print("112 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("113 Guardar el ultimo folio de embarque") # conseguir img orden de embarque
    folio_embarque = sge_funct.doubleclick_axis_y(img_folioEmbarque, 20)
    print("----------------------------")
    print(f"folio de embarque: {folio_embarque}")
    print("----------------------------")
    print("114 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("115 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("116 ingresar en el teclado la opcion de 7) Control de embarques")
    sge_funct.send_text('7')
    print("117 Teclear input")
    sge_funct.press_enter()
    print("118 ingresar en el teclado la opcion de 1) Enviar mercancia")
    sge_funct.send_text('1')
    print("119 Teclear input")
    sge_funct.press_enter()
    print("120 Teclear input")
    sge_funct.send_text(data["compañia_transporte"])  # al ingresar compañia de trasnporte
    print("120.1 Teclear input")
    sge_funct.press_enter()
    print("121 Presionar la combinacion de teclas: Ctrl + v")
    sge_funct.press_hotkeys('ctrl+v')
    print("122 ingresar en el teclado el codigo del vehiculo")
    sge_funct.send_text(data["codigo_vehiculo"])
    print("123 Teclear input")
    sge_funct.press_enter()
    print("124 Presionar la combinacion de teclas: Ctrl + e")
    sge_funct.press_hotkeys('ctrl+e')
    print("125 Teclear input")
    sge_funct.press_tab()
    print("126 ingresar en el teclado el nombre del chofer ")
    sge_funct.send_text(data["nombre_chofer"])
    sge_funct.segundos_de_espera(7)
    print("127 Teclear input")
    sge_funct.press_enter()
    print("128 Teclear input")
    sge_funct.press_enter()
    print("129 Teclear input para pegar la orden de embarque")
    sge_funct.send_text(folio_embarque)
    print("131 Teclear input")
    sge_funct.press_enter()
    print("132 Teclear input para ingresar la cajas")
    sge_funct.send_text(data["identificador_caja"])
    print("133 Teclear input")
    sge_funct.press_enter()
    print("134 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("135 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("136 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("137 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("138 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("139 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("140 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("141 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text(data["sucursal_destino"])
    sge_funct.validar_sucursal_seleccionada(data["sucursal_destino"])
    print("142 Teclear input")
    sge_funct.press_enter()
    print("143 Teclear input")
    sge_funct.send_text('2')
    print("144 Teclear input")
    sge_funct.press_enter()
    print("145 Seleccionar <<OPCION MENU>>")
    sge_funct.send_text('4')
    print("146 Teclear input ")
    sge_funct.press_enter()
    print("147 Seleccionar <<OPCION MENU>>")
    sge_funct.send_text('4')
    print("148 Teclear input")
    sge_funct.press_enter()
    print("149 Teclear input para pegar el vale de traspaso")
    sge_funct.send_text(vale_interno)
    print("150 Teclear input")
    sge_funct.press_enter()
    print("151 Teclear input")
    sge_funct.press_enter()
    print("152 Escribimos quien recibe la mercancia")
    sge_funct.send_text(data["nombre_recibe"])
    print("153 Teclear input")
    sge_funct.press_enter()
    print("154 Escribimos un comentario de recepcion")
    sge_funct.send_text(data["comentario_recepcion"])
    print("155 Teclear input")
    sge_funct.press_enter()
    print("156 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("157 Teclear input")
    sge_funct.press_enter()
    print("158 Capturar la cantidad 1")
    sge_funct.send_text(data["cantidad_a_mover"])
    print("159 Teclear input")
    sge_funct.press_enter()
    print("160 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("161 Teclear input")
    sge_funct.send_text('s')
    sge_funct.press_enter() #<------------- Agregado
    print("162 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("163 Ingresar en Login el <<Usuario Almacen>>")
    sge_funct.send_text(data["usuario_almacen"])
    print("164 Teclear input")
    sge_funct.press_enter()
