from Config.config import images


def MTC_SURSGE_005_steps(sge_funct, data):

    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text(data["sucursal"])
    sge_funct.segundos_de_espera(1)
    sge_funct.validar_sucursal_12_seleccionada()
    print("3 Teclear input")
    sge_funct.press_enter()
    print("4 Teclear input")
    sge_funct.send_text('2')
    print("5 Teclear input")
    sge_funct.press_enter()
    print("6 Teclear input")
    sge_funct.send_text('9')
    print("7 Teclear input")
    sge_funct.press_enter()
    print("8 Teclear input")
    sge_funct.send_text('12')
    print("9 Teclear input")
    sge_funct.press_enter()
    print("10 Presionar la combinacion de teclas: Ctrl + n")
    sge_funct.press_hotkeys('ctrl+n')
    print("11 Leer archivo workzone.json para capturar la clave del almacen")
    sge_funct.send_text(data["almacen"])
    print("12 Teclear input")
    sge_funct.press_enter()
    print("13 Leer archivo workzone.json para capturar la DESC. Work Zone")
    sge_funct.send_text(data["desc_workzone"])
    #se omite el paso 14
    print("15 Leer archivo workzone.json para capturar el pasillo desde")
    sge_funct.send_text(data["pasillo_desde"])
    print("16 Leer archivo workzone.json para capturar el pasillo hasta")
    sge_funct.send_text(data["pasillo_hasta"])
    print("17 Leer archivo workzone.json para capturar el bahia desde")
    sge_funct.send_text(data["bahia_desde"])
    print("18 Leer archivo workzone.json para capturar el bahia hasta")
    sge_funct.send_text(data["bahia_hasta"])
    print("19 Leer archivo workzone.json para capturar el nivel desde")
    sge_funct.send_text(data["nivel_desde"])
    print("20 Leer archivo workzone.json para capturar el nivel hasta")
    sge_funct.send_text(data["nivel_hasta"])
    print("21 Presionar la combinacion de teclas: Ctrl + w para guardar")
    sge_funct.press_hotkeys('ctrl+w')
