import logging


def MTC_SURSGE_022_steps(sge_funct, data):
    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text(data["sucursal_origen"])
    sge_funct.validar_sucursal_seleccionada(data["sucursal_origen"])
    print("3 Teclear input")
    sge_funct.press_enter()
    print("4 Teclear input")
    sge_funct.send_text('2')
    print("5 Teclear input")
    sge_funct.press_enter()
    print("6 Teclear input")
    sge_funct.send_text('9')
    print("7 Teclear input")
    sge_funct.press_enter()
    print("8 Teclear input")
    sge_funct.send_text('15')
    print("9 Teclear input")
    sge_funct.press_enter()
    print("10 Presionar la combinacion de teclas: Ctrl + n")
    sge_funct.press_hotkeys('ctrl+n')
    print("11 Leer archivo generar_entradas_inventario.json para capturar la clave del almacen")
    sge_funct.send_text(data['almacen'])
    print("12 Teclear input")
    sge_funct.press_enter()
    print("13 Leer archivo generar_entradas_inventario.json para capturar la clave DSO")
    sge_funct.send_text(data['clave_DSO'])
    print("14 Teclear input")
    sge_funct.press_enter()
    logging.info("************************************** PASO 15+++++++++++++++++++++++++++++++")
    print("15 Leer archivo generar_entradas_inventario.json para capturar la descripción")
    sge_funct.send_text(data['descripcion_DSO'])
    print("16 Teclear input")
    sge_funct.press_enter()
    print("17 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("18 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')
    print("19 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')
    logging.info("************************************** PASO 20+++++++++++++++++++++++++++++++")
    print("20 Teclear input")
    sge_funct.send_text('8')
    print("21 Teclear input")
    sge_funct.press_enter()
    print("22 Presionamos ctrl + f ")
    sge_funct.press_hotkeys('ctrl+f')
    print("23 Capturar a para dar de alta una zona")
    sge_funct.send_text('a')
    print("24 Leer archivo generar_entradas_inventario.json para capturar el Cedi")
    sge_funct.send_text(data['CEDI'])
    logging.info("************************************** PASO 25+++++++++++++++++++++++++++++++")
    print("25 Teclear input")
    sge_funct.press_enter()
    print("26 Leer archivo generar_entradas_inventario.json para capturar el almacen")
    sge_funct.send_text(data['almacen'])
    print("27 Teclear input")
    sge_funct.press_enter()
    print("28 Leer archivo generar_entradas_inventario.json para capturar la zona")
    sge_funct.send_text(data['zona'])
    print("29 Teclear input")
    sge_funct.press_enter()
    logging.info("************************************** PASO 30+++++++++++++++++++++++++++++++")
    print("30 Leer archivo generar_entradas_inventario.json para capturar la descripcion de la zona")
    sge_funct.send_text(data['descripcion_de_la_zona'])
    print("31 Teclear input")
    sge_funct.press_enter()
    print("32 Leer archivo generar_entradas_inventario.json para capturar DSO")
    sge_funct.send_text(data['clave_DSO'])
    print("33 Teclear input")
    sge_funct.press_enter()
    print("34 Capturar a para dar de alta una zona")
    sge_funct.send_text('a')

    print("45 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')
    print("45 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')
    print("46 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')
    print("47 Teclear input")
    sge_funct.send_text('12')
    print("48 Teclear input")
    sge_funct.press_enter()
    print("49 Presionar la combinacion de teclas: Ctrl + n")
    sge_funct.press_hotkeys('ctrl+n')
    print("50 Leer archivo generar_entradas_inventario.json para capturar la clave del almacen")
    sge_funct.send_text(data['almacen'])
    print("51 Teclear input")
    sge_funct.press_enter()
    print("52 Leer archivo generar_entradas_inventario.json para capturar la DESC. Work Zone")
    sge_funct.send_text(data['work_zone'])
    # print("53 Teclear input")
    # sge_funct.press_enter()
    print("54 Leer archivo generar_entradas_inventario.json para capturar el pasillo desde")
    sge_funct.send_text(data['pasillo_desde'])
    print("55 Leer archivo generar_entradas_inventario.json para capturar el pasillo hasta")
    sge_funct.send_text(data['pasillo_hasta'])
    print("56 Leer archivo generar_entradas_inventario.json para capturar el bahia desde")
    sge_funct.send_text(data['bahia_desde'])
    print("57 Leer archivo generar_entradas_inventario.json para capturar el bahia hasta")
    sge_funct.send_text(data['bahia_hasta'])
    print("58 Leer archivo generar_entradas_inventario.json para capturar el nivel desde")
    sge_funct.send_text(data['nivel_desde'])
    print("59 Leer archivo generar_entradas_inventario.json para capturar el nivel hasta")
    sge_funct.send_text(data['nivel_hasta'])
    print("60 Presionar la combinacion de teclas: Ctrl + w para guardar")
    sge_funct.press_hotkeys('ctrl+w')  # ERROR EL RANGO DE LA WORK ZONE ES INVALIDO, SE TRASLAPA CON OTRO REGISTRO
    print("61 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')

#-----------------------------------------------------------------------------------------------

    print("75 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')
    print("76 Teclear input")
    sge_funct.send_text('14')
    print("77 Teclear input")
    sge_funct.press_enter()
    print("78 Presionar la combinacion de teclas: Ctrl + n")
    sge_funct.press_hotkeys('ctrl+n')
    print("79 Leer archivo generar_entradas_inventario.json para capturar la clave del almacen")
    sge_funct.send_text(data['almacen'])
    print("80 Teclear input")
    sge_funct.press_enter()
    print("81 Capturar p")
    sge_funct.send_text('p')
    print(
        "82 Leer archivo generar_entradas_inventario.json para capturar localizacion que tenga pasillo, bahía y nivel referente a una work zone")
    sge_funct.send_text(data['localizacion'])
    sge_funct.press_enter()
    print("83 Presionar la combinacion de teclas: Ctrl + w para guardar")
    sge_funct.press_hotkeys('ctrl+w')
    print("84 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')
    print("85 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')

    print("97 Capturar la opcion Captura de localizaciones")
    sge_funct.send_text('8')
    print("98 Teclear input")
    sge_funct.press_enter()
    print("99 Leer archivo generar_entradas_inventario.json para capturar la clave del almacen")
    sge_funct.send_text(data['almacen'])
    print("100 Teclear input")
    sge_funct.press_enter()
    print("101 Leer archivo generar_entradas_inventario.json para capturar la linea del producto")
    sge_funct.send_text(data['linea'])
    print("102 Teclear input")
    sge_funct.press_enter()
    print("103 Leer archivo generar_entradas_inventario.json para capturar el codigo del producto")
    sge_funct.send_text(data['codigo'])
    print("104 Teclear input")
    sge_funct.press_enter()
    print("105 Teclear input")
    sge_funct.press_enter()
    print("106 Capturar la opcion 1 Localizaciones y Limites")
    sge_funct.send_text('1')
    print("107 Leer archivo generar_entradas_inventario.json para capturar la localizacion")
    sge_funct.send_text(data['localizacion'])
    print("108 Teclear input")
    sge_funct.press_enter()
    print("109 Leer archivo generar_entradas_inventario.json para capturar el minimo")
    sge_funct.send_text(data['minimo'])
    print("110 Teclear input")
    sge_funct.press_enter()
    print("111 Leer archivo generar_entradas_inventario.json para capturar el maximo")
    sge_funct.send_text(data['maximo'])
    print("112 Teclear input")
    sge_funct.press_enter()
    print("113 Presionar la combinacion de teclas: Ctrl + a para terminar")
    sge_funct.press_hotkeys('ctrl+a')
    print("114 ")
    sge_funct.press_hotkeys('ctrl+a')
    print("115 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')
    print("116 Capturar la opcion Captura de localizaciones")
    sge_funct.send_text('8')
    print("117 Teclear input")
    sge_funct.press_enter()
    print("118 Leer archivo generar_entradas_inventario.json para capturar la clave del almacen")
    sge_funct.send_text(data['almacen'])
    print("119 Teclear input")
    sge_funct.press_enter()
    print("120 Leer archivo generar_entradas_inventario.json para capturar la linea del producto")
    sge_funct.send_text(data['linea'])
    print("121 Teclear input")
    sge_funct.press_enter()
    print("122 Leer archivo generar_entradas_inventario.json para capturar el codigo del producto")
    sge_funct.send_text(data['codigo'])
    print("123 Teclear input")
    sge_funct.press_enter()
    print("124 Teclear input")
    sge_funct.press_enter()
    print("125 Capturar la opcion 2 Zonas")
    sge_funct.send_text('2')
    print("126 Leer archivo generar_entradas_inventario.json para capturar la zona")
    sge_funct.send_text(data['zona'])

    print("128 Presionar la combinacion de teclas: Ctrl + a para terminar")
    sge_funct.press_hotkeys('ctrl+a')
    print("129 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')
    print("130 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')
    print("131 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')
    print("132 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')
    print("133 Presionar la combinacion de teclas: Ctrl + A")
    sge_funct.press_hotkeys('ctrl+a')
    sge_funct.segundos_de_espera(2)
    print("134 Teclear input")
    sge_funct.activar_cambio_usuario()
    print("135 Teclear el nombre del usuario")
    sge_funct.send_text('sfabian0')
    print("136 Teclear input")
    sge_funct.press_enter()
    print("137 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text('12')
    sge_funct.validar_sucursal_seleccionada("12")
    print("138 Teclear input")
    sge_funct.press_enter()
    print("139 Teclear input")
    sge_funct.send_text('2')
    print("140 Teclear input")
    sge_funct.press_enter()
    print("141 Teclear input")
    sge_funct.send_text('9')
    print("142 Teclear input")
    sge_funct.press_enter()
    print("143 Capturar la opcion 13 Abastecimiento y Relleno")
    sge_funct.send_text('13')
    print("144 Teclear input")
    sge_funct.press_enter()
    print("145 Capturar c para consultar")
    sge_funct.send_text('c')
    print("146 Leer archivo generar_entradas_inventario.json para capturar la clave del almacen")
    sge_funct.send_text(data['almacen'])
    print("147 Teclear input")
    sge_funct.press_enter()
    print("148 Leer archivo generar_entradas_inventario.json para capturar la linea del producto")
    sge_funct.send_text(data['linea'])
    print("149 Teclear input")
    sge_funct.press_enter()
    print("150 Leer archivo generar_entradas_inventario.json para capturar el codigo del producto")
    sge_funct.send_text(data['codigo'])
    print("151 Teclear input")
    sge_funct.press_enter()
    print("152 Capturar m para modificar")
    sge_funct.send_text('m')
    sge_funct.segundos_de_espera(1)
    print("170 Flecha abajo para posicionarnos en la localización multiple")
    sge_funct.flecha_abajo()
    print("171 Presionar la combinacion de teclas: Ctrl + d para ver los detalles")
    sge_funct.press_hotkeys('ctrl+d')
    print("172 Leer archivo generar_entradas_inventario.json para capturar la localizacion destino")
    sge_funct.send_text(data['localizacion_destino'])
    print("173 Teclear input")
    sge_funct.press_enter()
    print("174 Leer archivo generar_entradas_inventario.json para capturar la cantidad a mover")
    sge_funct.send_text(data['cantidad_a_mover'])
    print("175 Teclear input")
    sge_funct.press_enter()
    print("176 Capturar s para continuar")
    sge_funct.send_text('s')
    print("177 Teclear input")
    sge_funct.press_enter()
    print("178 Teclear input")
    sge_funct.press_enter()

