import logging


def MTC_SURSGE_027_steps(sge_funct, data, img_valeInterno, img_folioEmbarque, cm_traspasos_file):

    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text(data["sucursal_origen"])
    sge_funct.validar_sucursal_seleccionada(data["sucursal_origen"])
    print("3 Teclear input")
    sge_funct.press_enter()
    print("4 Teclear input")
    sge_funct.send_text('2')
    print("5 Teclear input")
    sge_funct.press_enter()
    print("6 Seleccionar <<OPCION MENU>>")
    sge_funct.send_text('4')
    print("7 Teclear input ")
    sge_funct.press_enter()
    print("8 Seleccionar <<OPCION MENU>>")
    sge_funct.send_text('3')
    print("9 Teclear input")
    sge_funct.press_enter()
    print("10 Teclear input")
    sge_funct.send_text(data["sucursal_destino"])
    print("11 Teclear input")
    sge_funct.press_enter()
    print("12 Teclear input")
    sge_funct.press_enter()
    print("13 Teclear input")
    sge_funct.press_enter()
    print("14 Teclear input")
    sge_funct.press_enter()
    print("15 Teclear input")
    sge_funct.press_enter()
    print("17 Teclear input")
    sge_funct.press_enter()
    print("18 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("19 Leer archivo devolucion.json para capturar la linea del producto (LINEA 31) EJEMPLO")
    sge_funct.send_text(data["linea"])
    print("20 Teclear input")
    sge_funct.press_enter()
    print("21 Leer archivo devolucion.json para capturar el codigo del producto (CODIGO 1000) EJEMPLO")
    sge_funct.send_text(data["codigo"])
    print("22 Teclear input")
    sge_funct.press_enter()
    print("23 Leer archivo devolucion.json para capturar la cantidad")
    sge_funct.send_text(data["cantidad_a_mover"])
    print("24 Teclear input")
    sge_funct.press_enter()
    print("25 Teclear input")
    sge_funct.press_enter()
    print("26 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    sge_funct.segundos_de_espera(1)
    print("27 Guardar el Vale Interno dando doble clic en el Vale")
    vale_interno = sge_funct.doubleclick_axis_y(img_valeInterno,20)
    print("----------------------------")
    print(f"vale interno: {vale_interno}")
    print("----------------------------")
    print("28 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("29 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    logging.info("-----------------------------------------------Paso 30")
    print("30 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("31 Ingresar en el teclado el numero de pedidos e inventarios")
    sge_funct.send_text('4')
    print("32 Teclear input")
    sge_funct.press_enter()
    print("33 ingresar en el teclado la opcion de control de embarques")
    sge_funct.send_text('11')
    print("34 Teclear input ")
    sge_funct.press_enter()
    print("35 Teclear input")
    sge_funct.send_text('2')
    print("36 Teclear input")
    sge_funct.press_enter()
    print("37 ingresar en el teclado la opcion de Asignacion de documentos para surtido")
    sge_funct.send_text('1')
    print("38 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)
    #le agregue enviar vale interno
    sge_funct.send_text(vale_interno)

    print("39 Teclear input")
    sge_funct.press_enter()

    logging.info("-----------------------------------------------Paso 40")
    print("40 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("41 Teclear input")
    sge_funct.send_text(data["clave_surtidor"])
    print("42 Teclear input")
    sge_funct.press_enter()

    print("43 Teclear input")
    sge_funct.press_enter()

    print("44 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("45 ingresar en el teclado la opcion de 3# Marcar  Documentos como surtidos")
    sge_funct.send_text('3')
    print("46 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)#30
    #le agregue enviar vale interno
    sge_funct.send_text(vale_interno)
    print("47 Teclear input")
    sge_funct.press_enter()
    print("48 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("49 Teclear input")
    sge_funct.send_text(data["clave_surtidor"])
    logging.info("-----------------------------------------------Paso 50")
    print("50 Teclear input")
    sge_funct.press_enter()

    print("51 ingresar la contraseña del usuario de almacen")
    sge_funct.send_text(data["password_almacen"])
    print("52 Teclear input")
    sge_funct.press_enter()
    print("53 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(10)

    print("55 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("56 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("57 ingresar en el teclado la opcion de 3) Control de empaque")
    sge_funct.send_text('3')
    print("58 Teclear input")
    sge_funct.press_enter()
    print("59 ingresar en el teclado la opcion de 1) Documentos por empacar")
    sge_funct.send_text('1')
    logging.info("-----------------------------------------------Paso 60")
    print("60 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)#30
    sge_funct.send_text(vale_interno)
    print("61 Teclear input")
    sge_funct.press_enter()
    print("62 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("63 Teclear input")
    sge_funct.send_text(data["clave_empacador"])
    print("64 Teclear input")
    sge_funct.press_enter()
    print("65 ingresar la contraseña del usuario de almacen")
    sge_funct.send_text(data["password_almacen"])
    print("66 Teclear input")
    sge_funct.press_enter()
    print("67 Teclear input")
    sge_funct.press_enter()
    # print("68 Teclear input")
    # sge_funct.press_enter()
    print("69 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    logging.info("-----------------------------------------------Paso 70")
    print("70 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("71 ingresar en el teclado la opcion de 4) Termino de Empaque")
    sge_funct.send_text('4')
    print("72 Teclear input")
    sge_funct.press_enter()
    print("73 ingresar en el teclado la opcion de 1) Documentos por empacar")
    sge_funct.send_text('1')
    print("74 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)#30
    sge_funct.send_text(vale_interno)
    logging.info("-----------------------------------------------Paso 75")
    print("75 Teclear input")
    sge_funct.press_enter()
    print("76 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("77 Teclear input")
    sge_funct.send_text(data["clave_empacador"])
    print("78 Teclear input")
    sge_funct.press_enter()
    print("79 ingresar la contraseña del usuario de almacen")
    sge_funct.send_text(data["password_almacen"])
    logging.info("-----------------------------------------------Paso 80")
    print("80 Teclear input")
    sge_funct.press_enter()
    print("81 Teclear input")
    sge_funct.press_enter()

    # print("82 Teclear input")
    # sge_funct.press_enter()

    print("83 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("84 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    logging.info("-----------------------------------------------Paso 85")
    print("85 ingresar en el teclado la opcion de 5) Ordenes de embarque")
    sge_funct.send_text('5')
    print("86 Teclear input")
    sge_funct.press_enter()
    print("87 Flecha arriba para posicionarnos en la opcion TRASPASOS")
    sge_funct.flecha_arriba()
    print("88 Teclear input")
    sge_funct.press_enter()
    print("89 Teclear input para pegar el vale de traspaso")
    sge_funct.send_text(vale_interno)
    logging.info("-----------------------------------------------Paso 90")
    print("90 Teclear input")
    sge_funct.press_enter()
    print("91 Teclear input")
    sge_funct.press_enter()
    print("92 Teclear input")
    sge_funct.send_text(data["peso_embarque"])# original 999
    print("93 Teclear input")
    sge_funct.press_enter()
    print("94 Teclear input")
    sge_funct.send_text('1')
    logging.info("-----------------------------------------------Paso 95")
    print("95 Teclear input")
    sge_funct.press_enter()
    print("96 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("97 Teclear input")
    sge_funct.send_text(data["identificador_caja"])
    print("98 Teclear input")
    sge_funct.press_enter()
    print("99 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    logging.info("-----------------------------------------------Paso 100")
    print("100 Flecha abajo para el tipo de entrega OCURRE")
    sge_funct.flecha_abajo()
    print("101 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    sge_funct.segundos_de_espera(2)
    print("102 Guardar el ultimo folio de embarque")
    folio_embarque = sge_funct.doubleclick_axis_y(img_folioEmbarque, 20)
    print("----------------------------")
    print(f"folio de embarque: {folio_embarque}")
    print("----------------------------")
    print("103 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("104 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    logging.info("-----------------------------------------------Paso 105")
    print("105 ingresar en el teclado la opcion de 7) Control de embarques")
    sge_funct.send_text('7')
    print("106 Teclear input")
    sge_funct.press_enter()
    print("107 ingresar en el teclado la opcion de 1) Enviar mercancia")
    sge_funct.send_text('1')
    print("108 Teclear input")
    sge_funct.press_enter()
    print("109 Teclear input")
    sge_funct.send_text(data["compañia_transporte"])
    logging.info("-----------------------------------------------Paso 110")
    print("110 Teclear input")
    sge_funct.press_enter()
    print("111 Presionar la combinacion de teclas: Ctrl + v")
    sge_funct.press_hotkeys('ctrl+v')
    print("111.1 ingresar en el teclado el codigo del vehiculo")
    sge_funct.send_text(data["codigo_vehiculo"])
    print("112 Teclear input")
    sge_funct.press_enter()
    print("113 Presionar ctrl + E para regresar al menu")
    sge_funct.press_hotkeys('ctrl+e')
    print("114 Teclear input")
    sge_funct.press_tab()
    logging.info("-----------------------------------------------Paso 115")
    print("115 ingresar en el teclado el nombre del chofer ")
    sge_funct.send_text(data["nombre_chofer"])
    sge_funct.segundos_de_espera(7)
    print("115.1 Teclear input")
    sge_funct.press_enter()
    print("116 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)
    print("116.1 Teclear input para pegar la orden de embarque")
    sge_funct.send_text(folio_embarque)
    print("117 Teclear input")
    sge_funct.press_enter()
    print("118 Teclear input para ingresar la cajas")
    sge_funct.send_text(data["identificador_caja"])
    print("119 Teclear input")
    sge_funct.press_enter()
    logging.info("-----------------------------------------------Paso 120")
    print("120 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("121 presionar esc") # cambie el esc por ctrl+a
    sge_funct.press_hotkeys('ctrl+a')
    print("122 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("123 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("124 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    logging.info("-----------------------------------------------Paso 125")
    print("125 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("126 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("127 Presionar ctrl + A para regresar al menu") # le falto un ctrl+a
    sge_funct.press_hotkeys('ctrl+a')
    print("127.1 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text(data["sucursal_destino"])
    sge_funct.validar_sucursal_seleccionada(data["sucursal_destino"])
    print("128 Teclear input")
    sge_funct.press_enter()
    print("129 Teclear input")
    sge_funct.send_text('2')
    logging.info("-----------------------------------------------Paso 130")
    print("130 Teclear input")
    sge_funct.press_enter()
    print("131 Seleccionar <<OPCION MENU>>")
    sge_funct.send_text('4')
    print("132 Teclear input ")
    sge_funct.press_enter()
    print("133 Seleccionar <<OPCION MENU>>")
    sge_funct.send_text('4')
    print("134 Teclear input")
    sge_funct.press_enter()
    logging.info("-----------------------------------------------Paso 135")
    print("135 Teclear input para pegar el vale de traspaso")
    sge_funct.send_text(vale_interno)
    print("136 Teclear input")
    sge_funct.press_enter()
    print("137 Teclear input")
    sge_funct.press_enter()
    print("138 Escribimos quien recibe la mercancia")
    sge_funct.send_text(data["nombre_recibe"])
    print("139 Teclear input")
    sge_funct.press_enter()
    logging.info("-----------------------------------------------Paso 140")
    print("140 Escribimos un comentario de recepcion")
    sge_funct.send_text(data["comentario_recepcion"])
    print("141 Teclear input")
    sge_funct.press_enter()
    print("142 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("143 Teclear input")
    sge_funct.press_enter()
    print("144 Teclear input")
    sge_funct.press_enter()
    print("145 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    logging.info("-----------------------------------------------Paso 145")
    print("146 Teclear input")
    sge_funct.send_text('s')
    print("147 Teclear input")
    sge_funct.press_enter()
    print("148 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("149 Ingresar en Login el <<Usuario Almacen>>")
    sge_funct.send_text(data["usuario_almacen"])
    sge_funct.press_enter()