


def precondicion_mtc_SURSGE_028(sge_funct,img_utilerias_menu):

    print("step 1 En la pantalla sucursales Ingresar mm")
    sge_funct.activar_menu_mods()
    sge_funct.segundos_de_espera(1)
    assert sge_funct.validate_image_x(img_utilerias_menu), "No se ingreso en pantalla de MOD's"
    print("2 Teclear input")
    sge_funct.send_text('02')
    sge_funct.press_enter()
    print("31 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text('12')
    sge_funct.validar_sucursal_12_seleccionada()
    sge_funct.press_enter()
    print("4 Capturar b")
    sge_funct.send_text('b')
    sge_funct.press_tab()
    print("5 capturar almacen")
    sge_funct.send_text('01')
    sge_funct.press_enter()
    print("5 capturar linea")
    sge_funct.send_text('31')
    sge_funct.press_enter()
    print("6 teclear barra espacio 19 veces")
    for i in range(19):
        sge_funct.press_space()
    print("7 flecha izquierda 19 veces")
    for i in range(19):
        sge_funct.flecha_izquierda()
    print("8 capturar codigo")
    sge_funct.send_text('1000')
    sge_funct.press_enter()
    print("9 capturar m")
    sge_funct.send_text('m')
    print("10 capturar d16")
    sge_funct.send_text('d16')
    print("11 capturar 1.0000")
    sge_funct.send_text('1.0000')
    sge_funct.press_enter()
    print("12 capturar 99")
    sge_funct.send_text('99')
    sge_funct.press_enter()
    print("13 presionar 't' para terminar")
    sge_funct.send_text('t')
    sge_funct.segundos_de_espera(1)
    sge_funct.press_hotkeys('ctrl+a')
    assert sge_funct.validate_image_x(img_utilerias_menu), "No se ingreso en pantalla de MOD's"
    sge_funct.press_hotkeys('ctrl+a')
    sge_funct.press_hotkeys('ctrl+a')


def MTC_SURSGE_028_steps(sge_funct, data, img_valeInterno):

    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text(data['sucursal_origen'])
    sge_funct.validar_sucursal_seleccionada(data['sucursal_origen'])
    print("3 Teclear input")
    sge_funct.press_enter()
    print("4 Teclear input")
    sge_funct.send_text('2')
    print("5 Teclear input")
    sge_funct.press_enter()
    print("6 Seleccionar <<OPCION MENU>>")
    sge_funct.send_text('4')
    print("7 Teclear input ")
    sge_funct.press_enter()
    print("8 Seleccionar <<OPCION MENU>>")
    sge_funct.send_text('3')
    print("9 Teclear input")
    sge_funct.press_enter()
    print("10 Teclear input")
    sge_funct.send_text(data["sucursal_destino"])
    print("11 Teclear input")
    sge_funct.press_enter()
    print("12 Teclear input")
    sge_funct.press_enter()
    print("13 Teclear input")
    sge_funct.press_enter()
    print("14 Teclear input")
    sge_funct.press_enter()
    print("15 Teclear input")
    sge_funct.press_enter()
    print("16 Teclear input")
    sge_funct.press_enter()
    print("17 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("18 Presionar la combinacion de teclas: Ctrl + u")
    sge_funct.press_hotkeys('ctrl+u')
    print("19 Leer archivo surplus_carga_masiva.xml libro CM_traspasos para la carga masiva del traspaso")
    #sge_funct.leer_archivo_productos(cm_traspasos_file)
    #------------------ workaround paso 19  seguir los siguientes pasos:
    print("ingresar almacen")
    sge_funct.send_text(data["almacen"])
    sge_funct.press_tab()
    print("ingresar linea")
    sge_funct.send_text(data["linea"])
    sge_funct.press_tab()
    print("ingresar codigo")
    sge_funct.send_text(data["codigo"])
    sge_funct.press_tab()
    print("ingresar cantidad")
    sge_funct.send_text(data["cantidad_a_mover"])
    sge_funct.press_tab()
    # ------------------ workaround paso 19 fin

    print("20 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("21 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("22 Teclear input")
    sge_funct.press_enter()
    print("23 ingresar la contraseña del usuario de almacen")
    sge_funct.send_text(data["password_almacen"])
    print("24 Teclear input")
    sge_funct.press_enter()


    print("24 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(1)
    print("25 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    sge_funct.segundos_de_espera(1)
    print("26 Guardar el Vale Interno dando doble clic en el Vale")
    vale_interno = sge_funct.doubleclick_axis_y(img_valeInterno,20)
    print("----------------------------")
    print(vale_interno)
    print("----------------------------")
    print("27 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("28 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("29 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("30 Presionar ctrl + A para regresar al menu")
    sge_funct.press_hotkeys('ctrl+a')
    print("31 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text(data["sucursal_destino"])
    sge_funct.validar_sucursal_seleccionada(data["sucursal_destino"])
    print("32 Teclear input")
    sge_funct.press_enter()
    print("33 Teclear input")
    sge_funct.send_text('2')
    print("34 Teclear input")
    sge_funct.press_enter()
    print("35 Teclear input")
    sge_funct.send_text('4')
    print("36 Teclear input")
    sge_funct.press_enter()
    print("37 Teclear input")
    sge_funct.send_text('4')
    print("38 Teclear input")
    sge_funct.press_enter()
    print("39 Situarse en el campo vale interno e ingresar el numero del Vale Interno.")
    sge_funct.send_text(vale_interno)
    print("40 Teclear input")
    sge_funct.press_enter()
    print("41 Felcha abajo para seleccionar parcial")
    sge_funct.flecha_abajo()
    print("42 Teclear input")
    sge_funct.press_enter()
    print("43 Escribimos quien recibe la mercancia")
    sge_funct.send_text(data["nombre_recibe"])
    print("44 Teclear input")
    sge_funct.press_enter()
    print("45 Escribimos un comentario de recepcion")
    sge_funct.send_text(data["comentario_recepcion"])
    print("46 Teclear input")
    sge_funct.press_enter()
    print("47 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("48 Teclear input")
    sge_funct.press_enter()
    print("49 Capturar la cantidad 1")
    sge_funct.send_text(data["cantidad_a_mover"])
    print("50 Teclear input")
    sge_funct.press_enter()
    print("51 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')
    print("52 Teclear input")
    sge_funct.send_text('s')
    print("53 Teclear input")
    sge_funct.press_enter()
    print("54 Presionar la combinacion de teclas: Ctrl + w")
    sge_funct.press_hotkeys('ctrl+w')

    # print("55 Ingresar en Login el <<Usuario Almacen>>")
    # sge_funct.send_text('sfabian')
    # # #
